#pragma once

extern "C"
{
	VOID AlphaBlend2(ULONG,HBITMAP,ULONG,ULONG,ULONG,ULONG,HBITMAP,ULONG,ULONG,BOOL);
	VOID AlphaBlendScroller(ULONG,HBITMAP,ULONG,ULONG,ULONG,ULONG,HBITMAP,ULONG,ULONG,BOOL,ULONG,ULONG,ULONG);
	VOID PaintText(HDC,HBITMAP,HDC,HBITMAP,const LPCSTR strText,ULONG,ULONG);
}